"""tlog entry place detail fields

Revision ID: 0fb539e96bb9
Revises: 4eee289822ce
Create Date: 2026-03-21 21:52:45.628999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb539e96bb9'
down_revision = '4eee289822ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('primary_type_display_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('short_formatted_address', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('addr_locality', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('addr_admin_area_1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('addr_admin_area_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('addr_admin_area_3', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('addr_country_code', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_entry', schema=None) as batch_op:
        batch_op.drop_column('addr_country_code')
        batch_op.drop_column('addr_admin_area_3')
        batch_op.drop_column('addr_admin_area_2')
        batch_op.drop_column('addr_admin_area_1')
        batch_op.drop_column('addr_locality')
        batch_op.drop_column('short_formatted_address')
        batch_op.drop_column('primary_type_display_name')
        batch_op.drop_column('primary_type')

    # ### end Alembic commands ###
