"""Add soccer minutes v1 tables

Revision ID: 100489cd8284
Revises: 4460dc6a0c39
Create Date: 2026-09-14 22:28:30.900487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100489cd8284'
down_revision = '4460dc6a0c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('season_label', sa.String(length=80), nullable=True),
    sa.Column('period_count', sa.Integer(), nullable=False),
    sa.Column('formation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_team', schema=None) as batch_op:
        batch_op.create_index('ix_scm_team_user_id', ['user_id'], unique=False)

    op.create_table('scm_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent_name', sa.String(length=120), nullable=False),
    sa.Column('period_count', sa.Integer(), nullable=False),
    sa.Column('formation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft_assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_period', sa.Integer(), nullable=False),
    sa.Column('clock_running', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('last_resumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['scm_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_game', schema=None) as batch_op:
        batch_op.create_index('ix_scm_game_team_id', ['team_id'], unique=False)

    op.create_table('scm_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('jersey_number', sa.String(length=8), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['scm_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_player', schema=None) as batch_op:
        batch_op.create_index('ix_scm_player_team_id', ['team_id'], unique=False)

    op.create_table('scm_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('at_ms', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['scm_game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_event', schema=None) as batch_op:
        batch_op.create_index('ix_scm_event_game_id', ['game_id'], unique=False)

    op.create_table('scm_game_roster_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['scm_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['scm_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_scm_game_roster_entry_game_player')
    )
    with op.batch_alter_table('scm_game_roster_entry', schema=None) as batch_op:
        batch_op.create_index('ix_scm_game_roster_entry_game_id', ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_game_roster_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_game_roster_entry_game_id')

    op.drop_table('scm_game_roster_entry')
    with op.batch_alter_table('scm_event', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_event_game_id')

    op.drop_table('scm_event')
    with op.batch_alter_table('scm_player', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_player_team_id')

    op.drop_table('scm_player')
    with op.batch_alter_table('scm_game', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_game_team_id')

    op.drop_table('scm_game')
    with op.batch_alter_table('scm_team', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_team_user_id')

    op.drop_table('scm_team')
    # ### end Alembic commands ###
