"""Make meal location required

Revision ID: 1129ee779b0d
Revises: 2840136e51c3
Create Date: 2026-02-14 17:16:13.889617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1129ee779b0d'
down_revision = '2840136e51c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE meals_entry SET location = 'Home' WHERE location IS NULL OR location = ''")
    with op.batch_alter_table('meals_entry', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals_entry', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
