"""Add Ask Many LLMs models and user credits

Revision ID: 1ac6364b8679
Revises: d29e8e9f97b6
Create Date: 2025-12-05 01:22:49.997774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ac6364b8679'
down_revision = 'd29e8e9f97b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add credits column to user table first
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False, server_default='10'))
    
    # Create llm_question table WITHOUT the foreign key to llm_response
    op.create_table('llm_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('summary_response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create llm_response table (can reference llm_question now)
    op.create_table('llm_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('llm_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost', sa.Float(), nullable=True),
    sa.Column('output_cost', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['llm_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Now add the foreign key from llm_question to llm_response
    with op.batch_alter_table('llm_question', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_llm_question_summary_response_id', 'llm_response', ['summary_response_id'], ['id'])
    
    # Drop todo_items table if it exists
    op.drop_table('todo_items')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first
    with op.batch_alter_table('llm_question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_llm_question_summary_response_id', type_='foreignkey')
    
    # Drop tables
    op.drop_table('llm_response')
    op.drop_table('llm_question')
    
    # Restore todo_items table
    op.create_table('todo_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='todo_items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='todo_items_pkey')
    )
    
    # Drop credits column from user
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credits')
    # ### end Alembic commands ###
