"""Add SportsScheduleSavedQuery

Revision ID: 1cc4e0943a11
Revises: 1129ee779b0d
Create Date: 2026-02-17 23:39:01.354702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc4e0943a11'
down_revision = '1129ee779b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports_schedule_saved_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sports_schedule_saved_queries', schema=None) as batch_op:
        batch_op.create_index('ix_sports_schedule_saved_queries_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports_schedule_saved_queries', schema=None) as batch_op:
        batch_op.drop_index('ix_sports_schedule_saved_queries_user_id')

    op.drop_table('sports_schedule_saved_queries')
    # ### end Alembic commands ###
