"""Add connect4_online_room

Revision ID: 28c129f968a4
Revises: 2b1ddfe0708b
Create Date: 2026-09-05 00:06:27.310917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c129f968a4'
down_revision = '2b1ddfe0708b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect4_online_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('board', sa.JSON(), nullable=False),
    sa.Column('turn', sa.String(length=1), nullable=False),
    sa.Column('last_starter', sa.String(length=1), nullable=False),
    sa.Column('seat_x', sa.String(length=32), nullable=True),
    sa.Column('seat_o', sa.String(length=32), nullable=True),
    sa.Column('name_x', sa.String(length=30), nullable=True),
    sa.Column('name_o', sa.String(length=30), nullable=True),
    sa.Column('color_x', sa.String(length=16), nullable=True),
    sa.Column('color_o', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('winner', sa.String(length=1), nullable=True),
    sa.Column('winning_cells', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connect4_online_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connect4_online_room_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connect4_online_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connect4_online_room_code'))

    op.drop_table('connect4_online_room')
    # ### end Alembic commands ###
