"""Add baseball lineup v1 tables

Revision ID: 2b1ddfe0708b
Revises: b778126c64b8
Create Date: 2026-09-01 23:59:22.145883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b1ddfe0708b'
down_revision = 'b778126c64b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blu_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('season_label', sa.String(length=80), nullable=True),
    sa.Column('default_inning_count', sa.Integer(), nullable=False),
    sa.Column('default_expected_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blu_team', schema=None) as batch_op:
        batch_op.create_index('ix_blu_team_user_id', ['user_id'], unique=False)

    op.create_table('blu_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent_name', sa.String(length=120), nullable=False),
    sa.Column('inning_count', sa.Integer(), nullable=False),
    sa.Column('expected_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['blu_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blu_game', schema=None) as batch_op:
        batch_op.create_index('ix_blu_game_team_id', ['team_id'], unique=False)

    op.create_table('blu_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['blu_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blu_player', schema=None) as batch_op:
        batch_op.create_index('ix_blu_player_team_id', ['team_id'], unique=False)

    op.create_table('blu_game_roster_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['blu_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['blu_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_blu_game_roster_entry_game_player')
    )
    with op.batch_alter_table('blu_game_roster_entry', schema=None) as batch_op:
        batch_op.create_index('ix_blu_game_roster_entry_game_id', ['game_id'], unique=False)

    op.create_table('blu_lineup_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('position_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['blu_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['blu_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'inning', name='uq_blu_lineup_cell_game_player_inning')
    )
    with op.batch_alter_table('blu_lineup_cell', schema=None) as batch_op:
        batch_op.create_index('ix_blu_lineup_cell_game_id', ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blu_lineup_cell', schema=None) as batch_op:
        batch_op.drop_index('ix_blu_lineup_cell_game_id')

    op.drop_table('blu_lineup_cell')
    with op.batch_alter_table('blu_game_roster_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_blu_game_roster_entry_game_id')

    op.drop_table('blu_game_roster_entry')
    with op.batch_alter_table('blu_player', schema=None) as batch_op:
        batch_op.drop_index('ix_blu_player_team_id')

    op.drop_table('blu_player')
    with op.batch_alter_table('blu_game', schema=None) as batch_op:
        batch_op.drop_index('ix_blu_game_team_id')

    op.drop_table('blu_game')
    with op.batch_alter_table('blu_team', schema=None) as batch_op:
        batch_op.drop_index('ix_blu_team_user_id')

    op.drop_table('blu_team')
    # ### end Alembic commands ###
