"""helper task reminders

Revision ID: 3501076640e4
Revises: 55489d5634eb
Create Date: 2026-04-21 09:45:49.362318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3501076640e4'
down_revision = '55489d5634eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper_reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['helper_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helper_reminder_log', schema=None) as batch_op:
        batch_op.create_index('ix_helper_reminder_log_task_id', ['task_id'], unique=False)

    with op.batch_alter_table('helper_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_helper_task_reminder_at', ['reminder_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helper_task', schema=None) as batch_op:
        batch_op.drop_index('ix_helper_task_reminder_at')
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('reminder_at')

    with op.batch_alter_table('helper_reminder_log', schema=None) as batch_op:
        batch_op.drop_index('ix_helper_reminder_log_task_id')

    op.drop_table('helper_reminder_log')
    # ### end Alembic commands ###
