"""Add sports scores models

Revision ID: 39dbd3a6361b
Revises: e3f0bf53661b
Create Date: 2026-03-30 09:27:31.318902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dbd3a6361b'
down_revision = 'e3f0bf53661b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores_fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_key', sa.String(length=16), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores_fetch_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_fetch_log_sport_key'), ['sport_key'], unique=True)

    op.create_table('scores_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_event_id', sa.String(length=64), nullable=False),
    sa.Column('sport_key', sa.String(length=16), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=True),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status_state', sa.String(length=16), nullable=False),
    sa.Column('status_detail', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_event_id', 'sport_key', name='uq_scores_game_event_sport')
    )
    with op.batch_alter_table('scores_game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_game_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_game_sport_key'), ['sport_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_game_sport_key'))
        batch_op.drop_index(batch_op.f('ix_scores_game_game_date'))

    op.drop_table('scores_game')
    with op.batch_alter_table('scores_fetch_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_fetch_log_sport_key'))

    op.drop_table('scores_fetch_log')
    # ### end Alembic commands ###
