"""add ss_zip_codes and ss_geocode_cache tables

Revision ID: 3c5ef497f4bd
Revises: f5397a0a0cad
Create Date: 2026-05-03 07:22:24.303457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5ef497f4bd'
down_revision = 'f5397a0a0cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_geocode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'state', name='uq_ss_geocode_cache_city_state')
    )
    op.create_table('ss_zip_codes',
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('zip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ss_zip_codes')
    op.drop_table('ss_geocode_cache')
    # ### end Alembic commands ###
