"""add preferred_label to betfake_sport

Revision ID: 3e3f32e29ca4
Revises: 6cfcc02c64cf
Create Date: 2026-02-01 14:17:16.620263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3f32e29ca4'
down_revision = '6cfcc02c64cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betfake_sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betfake_sports', schema=None) as batch_op:
        batch_op.drop_column('preferred_label')

    # ### end Alembic commands ###
