"""Add password reset fields

Revision ID: 414b86d6fb7e
Revises: 7903184c6681
Create Date: 2025-12-05 16:48:05.427913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414b86d6fb7e'
down_revision = '7903184c6681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_expiry')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
