"""Add betfake models

Revision ID: 41e3381f2c48
Revises: 94f95948082e
Create Date: 2026-01-31 07:41:50.012936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e3381f2c48'
down_revision = '94f95948082e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betfake_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('sport_key', sa.String(length=100), nullable=False),
    sa.Column('sport_title', sa.String(length=100), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('away_team', sa.String(length=100), nullable=True),
    sa.Column('commence_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Scheduled', 'Live', 'Completed', name='gamestatus'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('betfake_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betfake_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('h2h', 'spreads', 'totals', 'outrights', name='markettype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('bookmaker_key', sa.String(length=100), nullable=False),
    sa.Column('external_market_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('marked_inactive_at', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['betfake_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betfake_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('outcome_name', sa.String(length=255), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('point_value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['betfake_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betfake_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('wager_amount', sa.Float(), nullable=False),
    sa.Column('odds_at_time', sa.Integer(), nullable=False),
    sa.Column('line_at_time', sa.Float(), nullable=True),
    sa.Column('outcome_name_at_time', sa.String(length=255), nullable=False),
    sa.Column('potential_payout', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Won', 'Lost', 'Push', name='betstatus'), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['betfake_accounts.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['betfake_outcomes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betfake_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('Wager', 'Payout', 'Account_Creation', name='transactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['betfake_accounts.id'], ),
    sa.ForeignKeyConstraint(['bet_id'], ['betfake_bets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betfake_transactions')
    op.drop_table('betfake_bets')
    op.drop_table('betfake_outcomes')
    op.drop_table('betfake_markets')
    op.drop_table('betfake_accounts')
    op.drop_table('betfake_games')
    # ### end Alembic commands ###
