"""update_list_editor_for_pending_invitations

Revision ID: 4267710fa14f
Revises: f10469e5e0c0
Create Date: 2025-12-08 22:48:29.968249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4267710fa14f'
down_revision = 'f10469e5e0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_editor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=60), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('list_editor_list_id_user_id_key', type_='unique')
        batch_op.create_unique_constraint('unique_list_email', ['list_id', 'email'])
        batch_op.create_unique_constraint('unique_list_user', ['list_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_editor', schema=None) as batch_op:
        batch_op.drop_constraint('unique_list_user', type_='unique')
        batch_op.drop_constraint('unique_list_email', type_='unique')
        batch_op.create_unique_constraint('list_editor_list_id_user_id_key', ['list_id', 'user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
