"""Add Kids AI tables

Revision ID: 4460dc6a0c39
Revises: 9ab548f54176
Create Date: 2026-09-09 21:14:52.045671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4460dc6a0c39'
down_revision = '9ab548f54176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kids_ai_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('age_tier', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('lock_count', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('kids_ai_child', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kids_ai_child_parent_user_id'), ['parent_user_id'], unique=False)

    op.create_table('kids_ai_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('kids_ai_consent_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('age_tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['kids_ai_child.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kids_ai_consent_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kids_ai_consent_event_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kids_ai_consent_event_parent_user_id'), ['parent_user_id'], unique=False)

    op.create_table('kids_ai_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('title_source', sa.String(length=20), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('running_summary', sa.Text(), nullable=True),
    sa.Column('last_flag_concern', sa.Text(), nullable=True),
    sa.Column('pass2_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['kids_ai_child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kids_ai_conversation', schema=None) as batch_op:
        batch_op.create_index('ix_kids_ai_conversation_child_locked', ['child_id', 'locked'], unique=False)
        batch_op.create_index('ix_kids_ai_conversation_child_modified', ['child_id', 'modified_at'], unique=False)

    op.create_table('kids_ai_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['kids_ai_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kids_ai_message', schema=None) as batch_op:
        batch_op.create_index('ix_kids_ai_message_conversation_created', ['conversation_id', 'created_at'], unique=False)

    op.create_table('kids_ai_llm_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('child_message_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('output_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['kids_ai_child.id'], ),
    sa.ForeignKeyConstraint(['child_message_id'], ['kids_ai_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['kids_ai_conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kids_ai_llm_call', schema=None) as batch_op:
        batch_op.create_index('ix_kids_ai_llm_call_child_created', ['child_id', 'created_at'], unique=False)
        batch_op.create_index('ix_kids_ai_llm_call_child_message', ['child_message_id'], unique=False)
        batch_op.create_index('ix_kids_ai_llm_call_kind_created', ['kind', 'created_at'], unique=False)
        batch_op.create_index('ix_kids_ai_llm_call_parent_created', ['parent_user_id', 'created_at'], unique=False)

    op.create_table('kids_ai_moderation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('child_message_id', sa.Integer(), nullable=False),
    sa.Column('assistant_message_id', sa.Integer(), nullable=True),
    sa.Column('pass_number', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('concern', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['kids_ai_message.id'], ),
    sa.ForeignKeyConstraint(['child_message_id'], ['kids_ai_message.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['kids_ai_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kids_ai_moderation_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kids_ai_moderation_result_child_message_id'), ['child_message_id'], unique=False)
        batch_op.create_index('ix_kids_ai_moderation_result_conversation_created', ['conversation_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kids_ai_moderation_result', schema=None) as batch_op:
        batch_op.drop_index('ix_kids_ai_moderation_result_conversation_created')
        batch_op.drop_index(batch_op.f('ix_kids_ai_moderation_result_child_message_id'))

    op.drop_table('kids_ai_moderation_result')
    with op.batch_alter_table('kids_ai_llm_call', schema=None) as batch_op:
        batch_op.drop_index('ix_kids_ai_llm_call_parent_created')
        batch_op.drop_index('ix_kids_ai_llm_call_kind_created')
        batch_op.drop_index('ix_kids_ai_llm_call_child_message')
        batch_op.drop_index('ix_kids_ai_llm_call_child_created')

    op.drop_table('kids_ai_llm_call')
    with op.batch_alter_table('kids_ai_message', schema=None) as batch_op:
        batch_op.drop_index('ix_kids_ai_message_conversation_created')

    op.drop_table('kids_ai_message')
    with op.batch_alter_table('kids_ai_conversation', schema=None) as batch_op:
        batch_op.drop_index('ix_kids_ai_conversation_child_modified')
        batch_op.drop_index('ix_kids_ai_conversation_child_locked')

    op.drop_table('kids_ai_conversation')
    with op.batch_alter_table('kids_ai_consent_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kids_ai_consent_event_parent_user_id'))
        batch_op.drop_index(batch_op.f('ix_kids_ai_consent_event_child_id'))

    op.drop_table('kids_ai_consent_event')
    op.drop_table('kids_ai_parent')
    with op.batch_alter_table('kids_ai_child', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kids_ai_child_parent_user_id'))

    op.drop_table('kids_ai_child')
    # ### end Alembic commands ###
