"""Add reminder table

Revision ID: 47072df4f5b5
Revises: 5ae6f0232d7a
Create Date: 2026-03-04 09:03:44.149096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47072df4f5b5'
down_revision = '5ae6f0232d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_user_remind_at', ['user_id', 'remind_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_user_remind_at')

    op.drop_table('reminder')
    # ### end Alembic commands ###
