"""Add ESPNCollegeTeam model

Revision ID: 478d79cce292
Revises: 1cc4e0943a11
Create Date: 2026-02-18 23:18:13.662654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478d79cce292'
down_revision = '1cc4e0943a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_college_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_team_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('league_code', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_team_id', 'league_code', name='_team_league_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espn_college_team')
    # ### end Alembic commands ###
