"""Add tlog_entry.day_period

Revision ID: 4e58fcd2eea8
Revises: 39dbd3a6361b
Create Date: 2026-04-13 19:42:17.054642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e58fcd2eea8'
down_revision = '39dbd3a6361b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_period', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_entry', schema=None) as batch_op:
        batch_op.drop_column('day_period')

    # ### end Alembic commands ###
