"""Add bg_color to tlog_tag

Revision ID: 4eee289822ce
Revises: 92d0ece0d681
Create Date: 2026-03-21 00:48:52.067144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eee289822ce'
down_revision = '92d0ece0d681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bg_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_tag', schema=None) as batch_op:
        batch_op.drop_column('bg_color')

    # ### end Alembic commands ###
