"""Add NFL survivor email reminder prefs

Revision ID: 4f0ed052632f
Revises: 100489cd8284
Create Date: 2026-09-15 22:58:29.139755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0ed052632f'
down_revision = '100489cd8284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_survivor_email_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_weekday', sa.Integer(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('nfl_survivor_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elimination_email_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_survivor_participants', schema=None) as batch_op:
        batch_op.drop_column('elimination_email_sent_at')

    op.drop_table('nfl_survivor_email_prefs')
    # ### end Alembic commands ###
