"""Add project field to LogEntry

Revision ID: 5365f3d9d079
Revises: 89b6222ab651
Create Date: 2025-12-02 00:09:25.521201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5365f3d9d079'
down_revision = '89b6222ab651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_column('project')

    # ### end Alembic commands ###
