"""helper_task completed_via_inbound_email_id

Revision ID: 55489d5634eb
Revises: 6a5dd4ee9a5d
Create Date: 2026-04-19 16:56:28.623489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55489d5634eb'
down_revision = '6a5dd4ee9a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helper_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_via_inbound_email_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'helper_inbound_email', ['completed_via_inbound_email_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helper_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('completed_via_inbound_email_id')

    # ### end Alembic commands ###
