"""add betfake sport model

Revision ID: 56e2f843ea8d
Revises: 41e3381f2c48
Create Date: 2026-02-01 09:36:48.444590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e2f843ea8d'
down_revision = '41e3381f2c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betfake_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_key', sa.String(length=100), nullable=False),
    sa.Column('sport_title', sa.String(length=100), nullable=False),
    sa.Column('has_spreads', sa.Boolean(), nullable=True),
    sa.Column('sync_scores', sa.Boolean(), nullable=True),
    sa.Column('sync_odds', sa.Boolean(), nullable=True),
    sa.Column('show_in_nav', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betfake_sports')
    # ### end Alembic commands ###
