"""add_google_oauth_fields

Revision ID: 573fb47d1f16
Revises: 414b86d6fb7e
Create Date: 2025-12-06 00:32:53.148844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573fb47d1f16'
down_revision = '414b86d6fb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_email', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
