"""Add swap request models

Revision ID: 5be2797447c7
Revises: a1b2c3d4e5f6
Create Date: 2025-12-12 15:29:16.367688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be2797447c7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_signup_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('requestor_family_member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['signup_list.id'], ),
    sa.ForeignKeyConstraint(['requestor_family_member_id'], ['family_member.id'], ),
    sa.ForeignKeyConstraint(['requestor_signup_id'], ['signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap_request_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swap_request_id', sa.Integer(), nullable=False),
    sa.Column('target_element_id', sa.Integer(), nullable=False),
    sa.Column('target_element_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['swap_request_id'], ['swap_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swap_request_id', 'target_element_id', 'target_element_type', name='unique_swap_request_target')
    )
    op.create_table('swap_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swap_request_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('recipient_signup_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_signup_id'], ['signup.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['swap_request_id'], ['swap_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swap_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swap_token_token'), ['token'], unique=True)

    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.drop_index('family_member_user_id_is_self_unique', postgresql_where='(is_self = true)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.create_index('family_member_user_id_is_self_unique', ['user_id'], unique=False, postgresql_where='(is_self = true)')

    with op.batch_alter_table('swap_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swap_token_token'))

    op.drop_table('swap_token')
    op.drop_table('swap_request_target')
    op.drop_table('swap_request')
    # ### end Alembic commands ###
