"""Add scheduled digest tables

Revision ID: 63418f73776c
Revises: f6cd1f9064e0
Create Date: 2026-03-13 23:33:24.144443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63418f73776c'
down_revision = 'f6cd1f9064e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports_schedule_scheduled_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_hour', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('sports_schedule_scheduled_digests', schema=None) as batch_op:
        batch_op.create_index('ix_sports_schedule_scheduled_digests_user_id', ['user_id'], unique=False)

    op.create_table('sports_schedule_scheduled_digest_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('saved_query_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['sports_schedule_scheduled_digests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_query_id'], ['sports_schedule_saved_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_id', 'saved_query_id', name='uq_digest_saved_query')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports_schedule_scheduled_digest_queries')
    with op.batch_alter_table('sports_schedule_scheduled_digests', schema=None) as batch_op:
        batch_op.drop_index('ix_sports_schedule_scheduled_digests_user_id')

    op.drop_table('sports_schedule_scheduled_digests')
    # ### end Alembic commands ###
