"""Add daily email models

Revision ID: 63f291808a7e
Revises: c1e16eb62415
Create Date: 2026-04-23 00:41:10.738600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f291808a7e'
down_revision = 'c1e16eb62415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_email_jobs_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ashby_slug', sa.String(length=255), nullable=True),
    sa.Column('filter_phrase', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('daily_email_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('send_hour_local', sa.Integer(), nullable=False),
    sa.Column('include_weather', sa.Boolean(), nullable=False),
    sa.Column('include_stocks', sa.Boolean(), nullable=False),
    sa.Column('include_sports', sa.Boolean(), nullable=False),
    sa.Column('include_jobs', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('daily_email_send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('modules_included', sa.String(length=100), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'digest_local_date', name='uix_daily_email_send_log_user_date')
    )
    with op.batch_alter_table('daily_email_send_log', schema=None) as batch_op:
        batch_op.create_index('ix_daily_email_send_log_user_id', ['user_id'], unique=False)

    op.create_table('daily_email_sports_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_code', sa.String(length=10), nullable=False),
    sa.Column('espn_team_id', sa.String(length=20), nullable=False),
    sa.Column('team_display_name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_email_sports_watch', schema=None) as batch_op:
        batch_op.create_index('ix_daily_email_sports_watch_user_id', ['user_id'], unique=False)

    op.create_table('daily_email_stock_ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_email_stock_ticker', schema=None) as batch_op:
        batch_op.create_index('ix_daily_email_stock_ticker_user_id', ['user_id'], unique=False)

    op.create_table('daily_email_weather_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_label', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_email_weather_location', schema=None) as batch_op:
        batch_op.create_index('ix_daily_email_weather_location_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_email_weather_location', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_email_weather_location_user_id')

    op.drop_table('daily_email_weather_location')
    with op.batch_alter_table('daily_email_stock_ticker', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_email_stock_ticker_user_id')

    op.drop_table('daily_email_stock_ticker')
    with op.batch_alter_table('daily_email_sports_watch', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_email_sports_watch_user_id')

    op.drop_table('daily_email_sports_watch')
    with op.batch_alter_table('daily_email_send_log', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_email_send_log_user_id')

    op.drop_table('daily_email_send_log')
    op.drop_table('daily_email_profile')
    op.drop_table('daily_email_jobs_config')
    # ### end Alembic commands ###
