"""helper tables

Revision ID: 6a5dd4ee9a5d
Revises: 4e58fcd2eea8
Create Date: 2026-04-16 08:04:46.395720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a5dd4ee9a5d'
down_revision = '4e58fcd2eea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inbound_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbound_email')
    )
    op.create_table('helper_group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['helper_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uix_helper_group_member_group_user')
    )
    op.create_table('helper_inbound_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sender_raw', sa.String(length=255), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('mailgun_timestamp', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['helper_group.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('helper_inbound_email', schema=None) as batch_op:
        batch_op.create_index('ix_helper_inbound_email_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_helper_inbound_email_group_id', ['group_id'], unique=False)
        batch_op.create_index('ix_helper_inbound_email_status', ['status'], unique=False)

    op.create_table('helper_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_email_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_email_id'], ['helper_inbound_email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helper_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_inbound_email_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['helper_group.id'], ),
    sa.ForeignKeyConstraint(['source_inbound_email_id'], ['helper_inbound_email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helper_task', schema=None) as batch_op:
        batch_op.create_index('ix_helper_task_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_helper_task_group_status', ['group_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helper_task', schema=None) as batch_op:
        batch_op.drop_index('ix_helper_task_group_status')
        batch_op.drop_index('ix_helper_task_created_at')

    op.drop_table('helper_task')
    op.drop_table('helper_action_log')
    with op.batch_alter_table('helper_inbound_email', schema=None) as batch_op:
        batch_op.drop_index('ix_helper_inbound_email_status')
        batch_op.drop_index('ix_helper_inbound_email_group_id')
        batch_op.drop_index('ix_helper_inbound_email_created_at')

    op.drop_table('helper_inbound_email')
    op.drop_table('helper_group_member')
    op.drop_table('helper_group')
    # ### end Alembic commands ###
