"""add is_outright to betfake sports

Revision ID: 6cfcc02c64cf
Revises: 56e2f843ea8d
Create Date: 2026-02-01 12:54:36.766978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfcc02c64cf'
down_revision = '56e2f843ea8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betfake_sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_outright', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betfake_sports', schema=None) as batch_op:
        batch_op.drop_column('is_outright')

    # ### end Alembic commands ###
