"""Add summary_response_id to Question model

Revision ID: 709ff6d2c891
Revises: efd5baea9cfb
Create Date: 2025-06-06 02:32:00.441792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709ff6d2c891'
down_revision = 'efd5baea9cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_response_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'response', ['summary_response_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('summary_response_id')

    # ### end Alembic commands ###
