"""add sport_group to betfake_sport

Revision ID: 7ef6f24a8835
Revises: 3e3f32e29ca4
Create Date: 2026-02-01 14:52:49.417916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef6f24a8835'
down_revision = '3e3f32e29ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betfake_sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_group', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betfake_sports', schema=None) as batch_op:
        batch_op.drop_column('sport_group')

    # ### end Alembic commands ###
