"""Add bowling models

Revision ID: 84c51929c358
Revises: c81f4e2b9aa3
Create Date: 2026-05-22 00:18:34.358853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c51929c358'
down_revision = 'c81f4e2b9aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bowling_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bowling_game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bowling_game_code'), ['code'], unique=True)

    op.create_table('bowling_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['bowling_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bowling_roll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('pins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['bowling_player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'frame', 'roll', name='uq_bowling_roll_player_frame_roll')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bowling_roll')
    op.drop_table('bowling_player')
    with op.batch_alter_table('bowling_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bowling_game_code'))

    op.drop_table('bowling_game')
    # ### end Alembic commands ###
