"""Replace daily_email_jobs_config with daily_email_job_watch

Revision ID: 8e0467bf1b07
Revises: 63f291808a7e
Create Date: 2026-04-23 08:21:20.197229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e0467bf1b07'
down_revision = '63f291808a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_email_job_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ats', sa.String(length=20), nullable=False),
    sa.Column('board_token', sa.String(length=255), nullable=False),
    sa.Column('filter_phrase', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ats', 'board_token', name='uix_daily_email_job_watch_user_ats_token')
    )
    with op.batch_alter_table('daily_email_job_watch', schema=None) as batch_op:
        batch_op.create_index('ix_daily_email_job_watch_user_id', ['user_id'], unique=False)

    op.drop_table('daily_email_jobs_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_email_jobs_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ashby_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('filter_phrase', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='daily_email_jobs_config_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_email_jobs_config_pkey'),
    sa.UniqueConstraint('user_id', name='daily_email_jobs_config_user_id_key')
    )
    with op.batch_alter_table('daily_email_job_watch', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_email_job_watch_user_id')

    op.drop_table('daily_email_job_watch')
    # ### end Alembic commands ###
