"""Add location_is_link field to Event model

Revision ID: 8fdae02d2d37
Revises: 4267710fa14f
Create Date: 2025-12-10 13:01:44.341894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdae02d2d37'
down_revision = '4267710fa14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_is_link', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location_is_link')

    # ### end Alembic commands ###
