"""add symbol columns to tic tac toe online room

Revision ID: 91a20db3e255
Revises: f2fc6a1bfefd
Create Date: 2026-08-22 00:01:04.396778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a20db3e255'
down_revision = 'f2fc6a1bfefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tic_tac_toe_online_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol_x', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('symbol_o', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tic_tac_toe_online_room', schema=None) as batch_op:
        batch_op.drop_column('symbol_o')
        batch_op.drop_column('symbol_x')

    # ### end Alembic commands ###
