"""Travel log tags

Revision ID: 92d0ece0d681
Revises: 63418f73776c
Create Date: 2026-03-21 00:36:09.103538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d0ece0d681'
down_revision = '63418f73776c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlog_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['tlog_collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tlog_tag', schema=None) as batch_op:
        batch_op.create_index('ix_tlog_tag_global_name', ['name'], unique=True, postgresql_where=sa.text("scope = 'global'"))
        batch_op.create_index('ix_tlog_tag_scope', ['scope'], unique=False)

    op.create_table('tlog_entry_tag',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['tlog_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tlog_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tlog_entry_tag')
    with op.batch_alter_table('tlog_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_tlog_tag_scope')
        batch_op.drop_index('ix_tlog_tag_global_name', postgresql_where=sa.text("scope = 'global'"))

    op.drop_table('tlog_tag')
    # ### end Alembic commands ###
