"""Add Note model for notes project

Revision ID: 94f95948082e
Revises: 3b4f0c34c0b2
Create Date: 2026-01-24 00:46:23.892718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f95948082e'
down_revision = '3b4f0c34c0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index('ix_note_user_archived_modified', ['user_id', 'is_archived', 'modified_at'], unique=False)
        batch_op.create_index('ix_note_user_modified', ['user_id', 'modified_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_user_modified')
        batch_op.drop_index('ix_note_user_archived_modified')

    op.drop_table('note')
    # ### end Alembic commands ###
