"""Add response_time to Response model

Revision ID: 96006dcc6083
Revises: 709ff6d2c891
Create Date: 2025-06-06 16:29:30.322192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96006dcc6083'
down_revision = '709ff6d2c891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('response_time')

    # ### end Alembic commands ###
