"""Add waitlist support: allow_waitlist field, WaitlistEntry model, and signup status

Revision ID: 9bc5c1ad60ef
Revises: c200e746fd7c
Create Date: 2025-12-13 20:25:10.240775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc5c1ad60ef'
down_revision = 'c200e746fd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.String(length=20), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_member.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['signup_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_type', 'element_id', 'family_member_id', name='unique_waitlist_entry')
    )
    
    # Add status column as nullable first
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE signup SET status = 'confirmed' WHERE status IS NULL")
    
    # Now make it NOT NULL
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    with op.batch_alter_table('signup_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_waitlist', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_list', schema=None) as batch_op:
        batch_op.drop_column('allow_waitlist')

    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('waitlist_entry')
    # ### end Alembic commands ###
