"""drop_cancelled_at_from_signup

Revision ID: 9c96b7137acd
Revises: d46caf09102c
Create Date: 2025-12-13 18:56:17.763552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c96b7137acd'
down_revision = 'd46caf09102c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
