"""add_full_name_and_short_name_to_user

Revision ID: 9e783ea91d5a
Revises: 573fb47d1f16
Create Date: 2025-12-08 16:28:20.921144

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e783ea91d5a"
down_revision = "573fb47d1f16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable with server default
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "full_name",
                sa.String(length=100),
                nullable=True,
                server_default="placeholder",
            )
        )
        batch_op.add_column(
            sa.Column(
                "short_name",
                sa.String(length=50),
                nullable=True,
                server_default="placeholder",
            )
        )

    # Update any existing NULL values to 'placeholder' (shouldn't be any, but just in case)
    op.execute("UPDATE \"user\" SET full_name = 'placeholder' WHERE full_name IS NULL")
    op.execute(
        "UPDATE \"user\" SET short_name = 'placeholder' WHERE short_name IS NULL"
    )

    # Now make columns non-nullable
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("full_name", nullable=False, server_default=None)
        batch_op.alter_column("short_name", nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("short_name")
        batch_op.drop_column("full_name")

    # ### end Alembic commands ###
