"""Add codenames online tables

Revision ID: 9f2262eff2fa
Revises: f19427eb1443
Create Date: 2026-09-05 12:15:34.610806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2262eff2fa'
down_revision = 'f19427eb1443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codenames_online_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('seat_x', sa.String(length=32), nullable=True),
    sa.Column('seat_o', sa.String(length=32), nullable=True),
    sa.Column('phone_role_x', sa.String(length=12), nullable=True),
    sa.Column('phone_role_o', sa.String(length=12), nullable=True),
    sa.Column('word_list_id', sa.String(length=32), nullable=True),
    sa.Column('exclude_confusing', sa.Boolean(), nullable=False),
    sa.Column('name_red', sa.String(length=30), nullable=True),
    sa.Column('name_blue', sa.String(length=30), nullable=True),
    sa.Column('words', sa.JSON(), nullable=True),
    sa.Column('key', sa.JSON(), nullable=True),
    sa.Column('revealed', sa.JSON(), nullable=True),
    sa.Column('turn', sa.String(length=5), nullable=True),
    sa.Column('winner', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codenames_online_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codenames_online_room_code'), ['code'], unique=True)

    op.create_table('codenames_confusing_word',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codenames_confusing_word')
    with op.batch_alter_table('codenames_online_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codenames_online_room_code'))

    op.drop_table('codenames_online_room')
    # ### end Alembic commands ###
