"""Add has_paid to nfl survivor participants

Revision ID: a610197547dd
Revises: ecce4408b966
Create Date: 2026-08-28 16:25:05.353078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a610197547dd'
down_revision = 'ecce4408b966'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('nfl_survivor_participants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('has_paid', sa.Boolean(), nullable=False, server_default='false')
        )

    with op.batch_alter_table('nfl_survivor_participants', schema=None) as batch_op:
        batch_op.alter_column('has_paid', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_survivor_participants', schema=None) as batch_op:
        batch_op.drop_column('has_paid')

    # ### end Alembic commands ###
