"""empty message

Revision ID: a7ca2906e69d
Revises: c04cd863b317
Create Date: 2026-09-28 20:32:21.303900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7ca2906e69d'
down_revision = 'c04cd863b317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bkm_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('season_label', sa.String(length=80), nullable=True),
    sa.Column('default_period_count', sa.Integer(), nullable=False),
    sa.Column('default_period_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bkm_team', schema=None) as batch_op:
        batch_op.create_index('ix_bkm_team_user_id', ['user_id'], unique=False)

    op.create_table('bkm_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent_name', sa.String(length=120), nullable=False),
    sa.Column('period_count', sa.Integer(), nullable=False),
    sa.Column('period_minutes', sa.Integer(), nullable=False),
    sa.Column('current_period', sa.Integer(), nullable=False),
    sa.Column('draft_lineup', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_lineup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_our_score', sa.Integer(), nullable=True),
    sa.Column('final_opponent_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['bkm_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bkm_game', schema=None) as batch_op:
        batch_op.create_index('ix_bkm_game_team_id', ['team_id'], unique=False)

    op.create_table('bkm_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('jersey_number', sa.String(length=8), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['bkm_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bkm_player', schema=None) as batch_op:
        batch_op.create_index('ix_bkm_player_team_id', ['team_id'], unique=False)

    op.create_table('bkm_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['bkm_game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bkm_event', schema=None) as batch_op:
        batch_op.create_index('ix_bkm_event_game_id', ['game_id'], unique=False)

    op.create_table('bkm_game_roster_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['bkm_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['bkm_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_bkm_game_roster_entry_game_player')
    )
    with op.batch_alter_table('bkm_game_roster_entry', schema=None) as batch_op:
        batch_op.create_index('ix_bkm_game_roster_entry_game_id', ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bkm_game_roster_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_bkm_game_roster_entry_game_id')

    op.drop_table('bkm_game_roster_entry')
    with op.batch_alter_table('bkm_event', schema=None) as batch_op:
        batch_op.drop_index('ix_bkm_event_game_id')

    op.drop_table('bkm_event')
    with op.batch_alter_table('bkm_player', schema=None) as batch_op:
        batch_op.drop_index('ix_bkm_player_team_id')

    op.drop_table('bkm_player')
    with op.batch_alter_table('bkm_game', schema=None) as batch_op:
        batch_op.drop_index('ix_bkm_game_team_id')

    op.drop_table('bkm_game')
    with op.batch_alter_table('bkm_team', schema=None) as batch_op:
        batch_op.drop_index('ix_bkm_team_user_id')

    op.drop_table('bkm_team')
    # ### end Alembic commands ###
