"""Add color to participants

Revision ID: aff3e8551f75
Revises: f70aa44a1b2d
Create Date: 2026-02-07 15:40:12.875189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff3e8551f75'
down_revision = 'f70aa44a1b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_squares_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
    
    # Set a default color for existing participants
    op.execute("UPDATE football_squares_participants SET color = '#e8f5e9' WHERE color IS NULL")
    
    with op.batch_alter_table('football_squares_participants', schema=None) as batch_op:
        batch_op.alter_column('color', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_squares_participants', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
