"""Add NFL Survivor models

Revision ID: b4b35893280c
Revises: c10f551b60b1
Create Date: 2026-08-28 14:27:42.885003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b35893280c'
down_revision = 'c10f551b60b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_survivor_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('join_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pick_week_2_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_week_2_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('season_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('espn_season_year', sa.Integer(), nullable=False),
    sa.Column('max_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('nfl_survivor_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['nfl_survivor_seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_nfl_survivor_participant')
    )
    op.create_table('nfl_survivor_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['nfl_survivor_seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', 'week', name='uq_nfl_survivor_pick')
    )
    op.create_table('nfl_survivor_spreads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('odds_id', sa.String(length=50), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('game_time', sa.DateTime(), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('road_team', sa.String(length=50), nullable=False),
    sa.Column('home_team_spread', sa.Float(), nullable=False),
    sa.Column('road_team_spread', sa.Float(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['nfl_survivor_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'odds_id', name='uq_nfl_survivor_spread_odds')
    )
    op.create_table('nfl_survivor_weekly_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['nfl_survivor_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'week', 'team', name='uq_nfl_survivor_weekly_result')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_survivor_weekly_results')
    op.drop_table('nfl_survivor_spreads')
    op.drop_table('nfl_survivor_picks')
    op.drop_table('nfl_survivor_participants')
    op.drop_table('nfl_survivor_seasons')
    # ### end Alembic commands ###
