"""add vs_cpu to battleship online room

Revision ID: b778126c64b8
Revises: b8e2c4f91a03
Create Date: 2026-08-31 00:33:45.871576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b778126c64b8'
down_revision = 'b8e2c4f91a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battleship_online_room', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('vs_cpu', sa.Boolean(), nullable=False, server_default='false')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battleship_online_room', schema=None) as batch_op:
        batch_op.drop_column('vs_cpu')

    # ### end Alembic commands ###
