"""Consolidate NFL Survivor season to week_2_start

Revision ID: c0004fd651bf
Revises: b4b35893280c
Create Date: 2026-08-28 14:51:48.732276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0004fd651bf'
down_revision = 'b4b35893280c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_survivor_seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_2_start', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('pick_week_2_start')
        batch_op.drop_column('game_week_2_start')
        batch_op.drop_column('join_deadline')
        batch_op.drop_column('season_start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_survivor_seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('join_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('game_week_2_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pick_week_2_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('week_2_start')

    # ### end Alembic commands ###
