"""Add soccer minutes goals

Revision ID: c04cd863b317
Revises: 4f0ed052632f
Create Date: 2026-09-20 19:49:43.535160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04cd863b317'
down_revision = '4f0ed052632f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('at_ms', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('scorer_id', sa.Integer(), nullable=True),
    sa.Column('assist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assist_id'], ['scm_player.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['scm_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scorer_id'], ['scm_player.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_goal', schema=None) as batch_op:
        batch_op.create_index('ix_scm_goal_game_id', ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_goal', schema=None) as batch_op:
        batch_op.drop_index('ix_scm_goal_game_id')

    op.drop_table('scm_goal')
    # ### end Alembic commands ###
