"""add battleship online room

Revision ID: c10f551b60b1
Revises: 91a20db3e255
Create Date: 2026-08-22 00:13:37.992877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10f551b60b1'
down_revision = '91a20db3e255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battleship_online_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('seat_x', sa.String(length=32), nullable=True),
    sa.Column('seat_o', sa.String(length=32), nullable=True),
    sa.Column('name_x', sa.String(length=30), nullable=True),
    sa.Column('name_o', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('turn', sa.String(length=1), nullable=False),
    sa.Column('winner', sa.String(length=1), nullable=True),
    sa.Column('fleet_x', sa.JSON(), nullable=True),
    sa.Column('fleet_o', sa.JSON(), nullable=True),
    sa.Column('shots_x', sa.JSON(), nullable=True),
    sa.Column('shots_o', sa.JSON(), nullable=True),
    sa.Column('ready_x', sa.Boolean(), nullable=False),
    sa.Column('ready_o', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battleship_online_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battleship_online_room_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battleship_online_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battleship_online_room_code'))

    op.drop_table('battleship_online_room')
    # ### end Alembic commands ###
