"""Update Response model to store input and output tokens separately

Revision ID: c131a6273e60
Revises: 91af2ce6a4c0
Create Date: 2025-06-05 18:17:06.628003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c131a6273e60'
down_revision = '91af2ce6a4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=True))
        batch_op.drop_column('tokens_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')

    # ### end Alembic commands ###
