"""make_signup_ids_nullable_in_swap_models

Revision ID: c200e746fd7c
Revises: da98fcca1da9
Create Date: 2025-12-13 19:21:14.305819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c200e746fd7c'
down_revision = 'da98fcca1da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_token', schema=None) as batch_op:
        batch_op.alter_column('recipient_signup_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_token', schema=None) as batch_op:
        batch_op.alter_column('recipient_signup_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
