"""add_target_element_to_swap_token

Revision ID: d46caf09102c
Revises: 5be2797447c7
Create Date: 2025-12-13 18:45:08.046410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46caf09102c'
down_revision = '5be2797447c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Delete existing swap tokens since we're adding new required fields
    # This is safe since swap tokens are temporary/ephemeral
    op.execute('DELETE FROM swap_token')
    
    # Add new columns
    with op.batch_alter_table('swap_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_element_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('target_element_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_token', schema=None) as batch_op:
        batch_op.drop_column('target_element_type')
        batch_op.drop_column('target_element_id')

    # ### end Alembic commands ###
