"""make_requestor_signup_id_nullable

Revision ID: da98fcca1da9
Revises: 9c96b7137acd
Create Date: 2025-12-13 19:19:24.184731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da98fcca1da9'
down_revision = '9c96b7137acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_request', schema=None) as batch_op:
        batch_op.alter_column('requestor_signup_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_request', schema=None) as batch_op:
        batch_op.alter_column('requestor_signup_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
