"""tlog collection editors (sharing)

Revision ID: e3f0bf53661b
Revises: 0fb539e96bb9
Create Date: 2026-03-21 23:04:26.762723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f0bf53661b'
down_revision = '0fb539e96bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlog_collection_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['tlog_collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id', name='uq_tlog_collection_member_collection_user')
    )
    with op.batch_alter_table('tlog_collection_member', schema=None) as batch_op:
        batch_op.create_index('ix_tlog_collection_member_collection_id', ['collection_id'], unique=False)
        batch_op.create_index('ix_tlog_collection_member_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tlog_collection_member', schema=None) as batch_op:
        batch_op.drop_index('ix_tlog_collection_member_user_id')
        batch_op.drop_index('ix_tlog_collection_member_collection_id')

    op.drop_table('tlog_collection_member')
    # ### end Alembic commands ###
