"""Add NFL Survivor games for kickoff lockout

Revision ID: ecce4408b966
Revises: c0004fd651bf
Create Date: 2026-08-28 15:46:27.711558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecce4408b966'
down_revision = 'c0004fd651bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_survivor_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('kickoff', sa.DateTime(), nullable=False),
    sa.Column('espn_event_id', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['nfl_survivor_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'week', 'team_id', name='uq_nfl_survivor_game')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_survivor_games')
    # ### end Alembic commands ###
