"""Add input_cost and output_cost to Response model

Revision ID: efd5baea9cfb
Revises: ba8a5df56db4
Create Date: 2025-06-06 02:09:56.888283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd5baea9cfb'
down_revision = 'ba8a5df56db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('output_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('output_cost')
        batch_op.drop_column('input_cost')

    # ### end Alembic commands ###
