"""Add lottery fields to SignupList, source field to Signup, and create LotteryEntry model

Revision ID: f016481f2d4f
Revises: ff76c9706357
Create Date: 2025-12-16 00:06:56.640769

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f016481f2d4f"
down_revision = "ff76c9706357"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lottery_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signup_list_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("family_member_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(event_id IS NOT NULL AND item_id IS NULL) OR (event_id IS NULL AND item_id IS NOT NULL)",
            name="lottery_entry_element_check",
        ),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["family_member_id"], ["family_member.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["signup_list_id"], ["signup_list.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add source column to signup table with proper handling of existing rows
    with op.batch_alter_table("signup", schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column("source", sa.String(length=20), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE signup SET source = 'direct' WHERE source IS NULL")

    # Now make it not null with server default
    with op.batch_alter_table("signup", schema=None) as batch_op:
        batch_op.alter_column("source", nullable=False, server_default="direct")

    # Add lottery columns to signup_list table with proper defaults
    with op.batch_alter_table("signup_list", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_lottery", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("lottery_datetime", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("lottery_timezone", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("lottery_completed", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("lottery_running", sa.Boolean(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE signup_list SET is_lottery = FALSE WHERE is_lottery IS NULL")
    op.execute(
        "UPDATE signup_list SET lottery_completed = FALSE WHERE lottery_completed IS NULL"
    )
    op.execute(
        "UPDATE signup_list SET lottery_running = FALSE WHERE lottery_running IS NULL"
    )

    # Now make boolean columns not null with server defaults
    with op.batch_alter_table("signup_list", schema=None) as batch_op:
        batch_op.alter_column("is_lottery", nullable=False, server_default="false")
        batch_op.alter_column(
            "lottery_completed", nullable=False, server_default="false"
        )
        batch_op.alter_column("lottery_running", nullable=False, server_default="false")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signup_list", schema=None) as batch_op:
        batch_op.drop_column("lottery_running")
        batch_op.drop_column("lottery_completed")
        batch_op.drop_column("lottery_timezone")
        batch_op.drop_column("lottery_datetime")
        batch_op.drop_column("is_lottery")

    with op.batch_alter_table("signup", schema=None) as batch_op:
        batch_op.drop_column("source")

    op.drop_table("lottery_entry")
    # ### end Alembic commands ###
