"""add_better_signups_models

Revision ID: f10469e5e0c0
Revises: 9e783ea91d5a
Create Date: 2025-12-08 17:42:58.305609

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "f10469e5e0c0"
down_revision = "9e783ea91d5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("is_self", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "is_self"),
    )
    op.create_table(
        "signup_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("list_password_hash", sa.String(length=128), nullable=True),
        sa.Column("accepting_signups", sa.Boolean(), nullable=True),
        sa.Column("list_type", sa.String(length=20), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signup_list", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signup_list_uuid"), ["uuid"], unique=True)

    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("event_datetime", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("spots_available", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["signup_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("spots_available", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["signup_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "list_editor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["signup_list.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("list_id", "user_id"),
    )
    op.create_table(
        "signup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("family_member_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(event_id IS NOT NULL AND item_id IS NULL) OR (event_id IS NULL AND item_id IS NOT NULL)"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_member_id"],
            ["family_member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "family_member_id", name="unique_event_signup"),
        sa.UniqueConstraint("item_id", "family_member_id", name="unique_item_signup"),
    )

    # Data migration: Create "self" family member for all existing users
    op.execute(
        text(
            """
        INSERT INTO family_member (user_id, display_name, is_self, created_at)
        SELECT id, full_name, true, CURRENT_TIMESTAMP
        FROM "user"
        WHERE NOT EXISTS (
            SELECT 1 
            FROM family_member fm 
            WHERE fm.user_id = "user".id AND fm.is_self = true
        )
    """
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signup")
    op.drop_table("list_editor")
    op.drop_table("item")
    op.drop_table("event")
    with op.batch_alter_table("signup_list", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signup_list_uuid"))

    op.drop_table("signup_list")
    op.drop_table("family_member")
    # ### end Alembic commands ###
