"""Add friend_wordle_room

Revision ID: f19427eb1443
Revises: 28c129f968a4
Create Date: 2026-09-05 00:20:22.651405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19427eb1443'
down_revision = '28c129f968a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_wordle_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('seat_x', sa.String(length=32), nullable=True),
    sa.Column('seat_o', sa.String(length=32), nullable=True),
    sa.Column('name_x', sa.String(length=30), nullable=True),
    sa.Column('name_o', sa.String(length=30), nullable=True),
    sa.Column('role_x', sa.String(length=10), nullable=True),
    sa.Column('role_o', sa.String(length=10), nullable=True),
    sa.Column('secret', sa.String(length=5), nullable=True),
    sa.Column('guesses', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friend_wordle_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_wordle_room_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_wordle_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_wordle_room_code'))

    op.drop_table('friend_wordle_room')
    # ### end Alembic commands ###
