"""Add tic_tac_toe_online_room

Revision ID: f2fc6a1bfefd
Revises: 84c51929c358
Create Date: 2026-08-21 23:47:12.295362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fc6a1bfefd'
down_revision = '84c51929c358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tic_tac_toe_online_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('board', sa.JSON(), nullable=False),
    sa.Column('turn', sa.String(length=1), nullable=False),
    sa.Column('last_starter', sa.String(length=1), nullable=False),
    sa.Column('seat_x', sa.String(length=32), nullable=True),
    sa.Column('seat_o', sa.String(length=32), nullable=True),
    sa.Column('name_x', sa.String(length=30), nullable=True),
    sa.Column('name_o', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('winner', sa.String(length=1), nullable=True),
    sa.Column('winning_line', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tic_tac_toe_online_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tic_tac_toe_online_room_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tic_tac_toe_online_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tic_tac_toe_online_room_code'))

    op.drop_table('tic_tac_toe_online_room')
    # ### end Alembic commands ###
