"""add daily email include_helper_tasks and also reminders

Revision ID: f5397a0a0cad
Revises: 8e0467bf1b07
Create Date: 2026-04-23 10:03:10.439321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5397a0a0cad'
down_revision = '8e0467bf1b07'
branch_labels = None
depends_on = None


def upgrade():
    # New NOT NULL boolean columns: existing daily_email_profile rows need a
    # server default for PostgreSQL to accept ADD COLUMN, then we drop the default.
    with op.batch_alter_table('daily_email_profile', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "include_reminders",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("true"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "include_helper_tasks",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("true"),
            )
        )
    with op.batch_alter_table("daily_email_profile", schema=None) as batch_op:
        batch_op.alter_column("include_reminders", server_default=None)
        batch_op.alter_column("include_helper_tasks", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_email_profile', schema=None) as batch_op:
        batch_op.drop_column('include_helper_tasks')
        batch_op.drop_column('include_reminders')

    # ### end Alembic commands ###
