"""Add travel log models

Revision ID: f6cd1f9064e0
Revises: 47072df4f5b5
Create Date: 2026-03-11 23:47:58.645670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cd1f9064e0'
down_revision = '47072df4f5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlog_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tlog_collection', schema=None) as batch_op:
        batch_op.create_index('ix_tlog_collection_user_last_modified', ['user_id', 'last_modified'], unique=False)

    op.create_table('tlog_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visited_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['tlog_collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tlog_entry', schema=None) as batch_op:
        batch_op.create_index('ix_tlog_entry_collection_id', ['collection_id'], unique=False)
        batch_op.create_index('ix_tlog_entry_user_id', ['user_id'], unique=False)

    op.create_table('tlog_entry_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('r2_key', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['tlog_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tlog_entry_photo')
    with op.batch_alter_table('tlog_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_tlog_entry_user_id')
        batch_op.drop_index('ix_tlog_entry_collection_id')

    op.drop_table('tlog_entry')
    with op.batch_alter_table('tlog_collection', schema=None) as batch_op:
        batch_op.drop_index('ix_tlog_collection_user_last_modified')

    op.drop_table('tlog_collection')
    # ### end Alembic commands ###
