"""Add football_squares models

Revision ID: f70aa44a1b2d
Revises: 7ef6f24a8835
Create Date: 2026-02-07 14:13:21.154148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70aa44a1b2d'
down_revision = '7ef6f24a8835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('football_squares_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('share_slug', sa.String(length=100), nullable=False),
    sa.Column('team1_name', sa.String(length=100), nullable=False),
    sa.Column('team1_color_primary', sa.String(length=7), nullable=False),
    sa.Column('team1_color_secondary', sa.String(length=7), nullable=False),
    sa.Column('team2_name', sa.String(length=100), nullable=False),
    sa.Column('team2_color_primary', sa.String(length=7), nullable=False),
    sa.Column('team2_color_secondary', sa.String(length=7), nullable=False),
    sa.Column('axis_type', sa.Enum('Draft', 'Random', name='axistype'), nullable=False),
    sa.Column('team1_digits', sa.String(length=100), nullable=False),
    sa.Column('team2_digits', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_slug')
    )
    op.create_table('football_squares_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('square_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['football_squares_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('football_squares_quarters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('quarter_number', sa.Integer(), nullable=False),
    sa.Column('team1_score', sa.Integer(), nullable=True),
    sa.Column('team2_score', sa.Integer(), nullable=True),
    sa.Column('payout_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['football_squares_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('football_squares_squares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['football_squares_grids.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['football_squares_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('football_squares_squares')
    op.drop_table('football_squares_quarters')
    op.drop_table('football_squares_participants')
    op.drop_table('football_squares_grids')
    # ### end Alembic commands ###
