"""Add max_signups_per_member to SignupList

Revision ID: ff76c9706357
Revises: 9bc5c1ad60ef
Create Date: 2025-12-15 15:29:53.021170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff76c9706357'
down_revision = '9bc5c1ad60ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_signups_per_member', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_list', schema=None) as batch_op:
        batch_op.drop_column('max_signups_per_member')

    # ### end Alembic commands ###
